{{- if .Values.kafkaProducer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: {{ include "data-platform.namespace" . }}
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: {{ include "data-platform.namespace" . }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for Kafka..."
              until kubectl wait --for=condition=Ready statefulset/kafka -n $NAMESPACE; do
                echo "Kafka not ready. Retrying in 5s..."
                sleep 5
              done
              echo "Waiting for Kafdrop..."
              until kubectl wait --for=condition=Available deployment/kafdrop -n $NAMESPACE; do
                 echo "Kafdrop not ready. Retrying in 5s..."
                 sleep 5
              done
              echo "All systems go!"
              
      restartPolicy: Always
      serviceAccountName: default 
      containers:
        - name: kafka-producer
          image: "{{ .Values.kafkaProducer.image }}:{{ .Values.kafkaProducer.tag }}"
          imagePullPolicy: {{ .Values.kafkaProducer.pullPolicy }}
          env:
            - name: BOOTSTRAP_SERVERS
              value: "{{ .Values.kafkaProducer.bootstrapServers }}"
            - name: TOPIC_NAME
              value: "{{ .Values.kafkaProducer.topic }}"
            - name: PYTHONPATH
              value: "/app"
{{- end }}