{{- if .Values.minio.enabled }}

# ==========================
# MinIO SERVICE
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ include "data-platform.namespace" . }}
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.apiPort }}
      targetPort: {{ .Values.minio.apiPort }}
      nodePort: {{ .Values.minio.apiNodePort }}
    - name: console
      port: {{ .Values.minio.consolePort }}
      targetPort: {{ .Values.minio.consolePort }}
      nodePort: {{ .Values.minio.consoleNodePort }}

---
# ==========================
# MinIO DEPLOYMENT
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ include "data-platform.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image }}:{{ .Values.minio.tag }}"
          args:
            - "server"
            - "--console-address"
            - ":{{ .Values.minio.consolePort }}"
            - "/data"
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.minio.accessKey }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.minio.secretKey }}"
          ports:
            - containerPort: {{ .Values.minio.apiPort }}
            - containerPort: {{ .Values.minio.consolePort }}

---
# ==========================
# Job: AUTO CREATE BUCKET
# ==========================
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: {{ include "data-platform.namespace" . }}
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never

      # Wait for MinIO to be READY
      initContainers:
        - name: wait-for-minio
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for MinIO...";
              until nc -z minio {{ .Values.minio.apiPort }}; do
                echo "MinIO not ready â€” retrying in 2s";
                sleep 2;
              done
              echo "MinIO is ready!"

      containers:
        - name: create-bucket
          image: quay.io/minio/mc:latest
          command:
            - sh
            - -c
            - |
              echo "Setting mc alias...";
              mc alias set local http://minio:{{ .Values.minio.apiPort }} {{ .Values.minio.accessKey }} {{ .Values.minio.secretKey }};

              echo "Creating bucket if not exist...";
              mc mb --ignore-existing local/{{ .Values.minio.defaultBucket }};

              echo "Done creating bucket."

{{- end }}
