{{- if .Values.pyiceberg.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyiceberg
  namespace: {{ include "data-platform.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyiceberg
  template:
    metadata:
      labels:
        app: pyiceberg
    spec:
      containers:
        - name: pyiceberg
          image: "{{ .Values.pyiceberg.image }}:{{ .Values.pyiceberg.tag }}"
          imagePullPolicy: IfNotPresent
{{- end }}
