# ./helm/templates/rbac-flink-submitter.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-wait-role
  namespace: {{ include "data-platform.namespace" . }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "watch", "list"] 
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"] 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-wait-binding
  namespace: {{ include "data-platform.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-wait-role
subjects:
- kind: ServiceAccount
  name: default 
  namespace: {{ include "data-platform.namespace" . }}